/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Prankur Agarwal
 */
public class New_Bill extends javax.swing.JFrame {

    /**
     * Creates new form New_Bill
     */
    public New_Bill() {
        initComponents();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 75, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 119, -1, -1));

        jButton1.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(225, 0, 0));
        jButton1.setText("Discard");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 178, -1, 37));

        jButton2.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 178, -1, 37));

        jLabel2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel2.setText("Patient Id:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 26, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel3.setText("Doctor Number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 75, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel4.setText("Prescription ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 126, -1, -1));

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 26, 150, -1));

        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 71, 150, -1));

        jTextField3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 120, 150, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 26, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/New_Bill.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 230));

        setSize(new java.awt.Dimension(398, 226));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new HomePage().setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 Calendar c=Calendar.getInstance();
        int cur_year=c.get(Calendar.YEAR);
        int cur_month=c.get(Calendar.MONTH) +1;
        int cur_day=c.get(Calendar.DAY_OF_MONTH);
        String cm,cd;
if (cur_month<10) {
cm=""+0+cur_month;   } else{ cm=""+cur_month;  }
if(cur_day<10)
{  cd=""+0+cur_day;  }  else  {    cd=""+cur_day;}
String date=cur_year+cm+cd;
        if(jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty()||
                jTextField3.getText().isEmpty()) 
   {
if(jTextField1.getText().isEmpty()) {
jLabel1.setVisible(true);}
if(jTextField2.getText().isEmpty()) {
jLabel6.setVisible(true);}
if(jTextField3.getText().isEmpty()) {
jLabel7.setVisible(true);}
JOptionPane.showMessageDialog(this,"Please enter the indicated fields.");
        }
else {
try {
                    jLabel1.setVisible(false);  jLabel6.setVisible(false);
                    jLabel7.setVisible(false);
                    String patientid=(String)jTextField1.getText();
                    String pid=(String)jTextField2.getText();
                    String dno=(String)jTextField3.getText();
                    
Class.forName("java.sql.DriverManager");
Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/mrproject","root","");
Statement s =(Statement) con.createStatement();
String qcc=jTextField3.getText();
String qc="SELECT * FROM invoice WHERE pid='"+qcc+"';";
 ResultSet rsc=s.executeQuery(qc);
 if(rsc.next())
 {
     JOptionPane.showMessageDialog(this,"Bill has already being generated....");
     jTextField1.setText("");
     jTextField2.setText("");
     jTextField3.setText("");
 }
else
 {String qpp=jTextField1.getText();
String qp="SELECT MAX(pno) FROM patient;";
ResultSet rsp=s.executeQuery(qp);
if(rsp.next())
 {
     String rspp=rsp.getString("MAX(pno)");
     if(Integer.parseInt(rspp)< Integer.parseInt(qpp))
     {
         JOptionPane.showMessageDialog(this,"Please enter proper Patient Id..");
         jTextField1.setText("");
     }
 else
 {
     
   String a=jTextField3.getText();  
String pr="SELECT pno FROM prescription WHERE pid='"+a+"';";
  ResultSet rsq=s.executeQuery(pr);   
   if(rsq.next())  
   {
       int pnnm= Integer.parseInt(rsq.getString("pno"));
     if(Integer.parseInt(jTextField1.getText())==pnnm)  
      
     {
String q5="INSERT INTO invoice (pid,pno,dno,bill_date,amount,modepay) VALUES(NULL,NULL,NULL,NULL,NULL,NULL);";
    s.executeUpdate(q5);

String q1="SELECT MAX(inno) FROM invoice;";
ResultSet rs=s.executeQuery(q1);
String i;
if(rs.next())
{
i=rs.getString("MAX(inno)");
String q="UPDATE invoice SET pid='"+dno+"',pno='"+patientid+"',dno='"+pid+"',bill_date='"+date+"' WHERE inno='"+i+"';";
s.executeUpdate(q);              
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
new New_Bill2(pid,dno).setVisible(true);
this.dispose();
}
else
{
    JOptionPane.showMessageDialog(this,"No record found...");
}                  
     }
  else
     {
         JOptionPane.showMessageDialog(this,"Please enter correct prescription ID.");
         jTextField3.setText("");
        jLabel7.setVisible(true);
     }
   } 

 }    
 }
 }
  } 
  
  catch(Exception e) 
  { JOptionPane.showMessageDialog(this, e.getMessage()); }
            }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char kc=evt.getKeyChar();
    if(!((kc>='0'&&kc<='9')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE)))
       {
           JOptionPane.showMessageDialog(this, "Please enter the correct patient ID.");
       evt.consume();
       }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        char kc=evt.getKeyChar();
    if(!((kc>='0'&&kc<='9')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE)))
       {
           JOptionPane.showMessageDialog(this, "Please enter the correct doctor ID.");
       evt.consume();
       }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
      char kc=evt.getKeyChar();
    if(!((kc>='0'&&kc<='9')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE)))
       {
           JOptionPane.showMessageDialog(this, "Please enter the correct prescription ID.");
       evt.consume();
       }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
this.setBackground(new Color(0,0,0,0));
jLabel1.setVisible(false);
jLabel6.setVisible(false);
jLabel7.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
