/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Prankur Agarwal
 */
public class New_Bill2 extends javax.swing.JFrame {
    public String pid1;
  public String dno1;
    /**
     * Creates new form New_Bill2
     */
    public New_Bill2() {
        initComponents();
    }
    New_Bill2(String pid, String dno) {
    pid1=pid;
    dno1=dno;
    initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "Cash", "Credit Card", "Debit Card" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 74, -1, 25));

        jButton1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel1.setText("Amount:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 26, -1, -1));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 21, 147, -1));

        jLabel2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel2.setText("Mode of payment:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(225, 0, 0));
        jLabel5.setText("*");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 74, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/New_Bill2.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 170));

        setSize(new java.awt.Dimension(358, 166));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DefaultComboBoxModel model=(DefaultComboBoxModel)jComboBox1.getModel();
        if(jComboBox1.getSelectedIndex()==0) {
                jLabel5.setVisible(true);
            JOptionPane.showMessageDialog(this,"Please enter the indicated fields.");}

 else {
                try {
 jLabel5.setVisible(false);
String mode=(String)model.getSelectedItem();
                    Class.forName("java.sql.DriverManager");
                    Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/mrproject","root","");
                    Statement s =(Statement) con.createStatement();
 String q1="SELECT MAX(inno) FROM invoice;";
ResultSet rs=s.executeQuery(q1);
String i;
if(rs.next())
{  
    String amount=jTextField4.getText();
i=rs.getString("MAX(inno)");
String q="UPDATE invoice SET amount='"+amount+"', modepay='"+mode+"' WHERE inno='"+i+"';";
s.executeUpdate(q);
                    JOptionPane.showMessageDialog(this,"Insertion sucessful..."+"\n The Invoice ID is "+i);
                    jTextField4.setText("");
                   jComboBox1.setSelectedIndex(0);
}
new New_Bill3().setVisible(true);
this.dispose();

                } catch(Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped

    }//GEN-LAST:event_jTextField4KeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
this.setBackground(new Color(0,0,0,0));
        jLabel5.setVisible(false);
try{
Class.forName("java.sql.DriverManager");
                    Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/mrproject","root","");
                    Statement s =(Statement) con.createStatement();    
String q2="SELECT charge FROM doctor WHERE  dno='"+pid1+"';";
   ResultSet rs3=s.executeQuery(q2);
   if(rs3.next())
   {
 String a1=  rs3.getString("charge");

 String q3="SELECT cost FROM prescription WHERE  pid='"+dno1+"';";
ResultSet rs4=s.executeQuery(q3);
if(rs4.next())
{
String a2=  rs4.getString("cost");

int a3= Integer.parseInt(a1)+ Integer.parseInt(a2);
jTextField4.setText(a3+"");
}
   }
}
catch(Exception ea)
{
    JOptionPane.showMessageDialog(this, ea);
}
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Bill2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Bill2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Bill2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Bill2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Bill2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
