/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Prankur Agarwal
 */
public class New_Prescription extends javax.swing.JFrame {

    /**
     * Creates new form New_Prescription
     */
    public New_Prescription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(225, 0, 0));
        jLabel11.setText("*");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 193, 12, -1));

        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 148, 105, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(225, 0, 0));
        jLabel14.setText("*");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 239, -1, -1));

        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 57, 105, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(225, 0, 0));
        jLabel9.setText("*");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 107, -1, -1));

        jTextField6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField6.setToolTipText("Enter the previous Prescription ID with the same Doctor(if ANY)");
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 240, 107, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(225, 0, 0));
        jLabel10.setText("*");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 147, -1, -1));

        jTextField5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 194, 105, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(225, 0, 0));
        jLabel7.setText("*");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 12, -1, -1));

        jLabel13.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel13.setText("Reference Number(previous ID):");
        jLabel13.setToolTipText("");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, -1, -1));

        jTextField3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 102, 105, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(225, 0, 0));
        jLabel8.setText("*");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 56, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel6.setText("Prescription:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 299, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel5.setText("Cost Of Prescription:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 199, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(225, 0, 0));
        jLabel12.setText("*");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 299, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel2.setText("Doctor ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, 83, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 293, 294, 192));

        jButton1.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 512, -1, -1));

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel1.setText("Patient ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel4.setText("Number of days:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 153, -1, -1));

        jButton2.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 512, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel3.setText("Visit Number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, -1, -1));

        jButton3.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(225, 0, 0));
        jButton3.setText("Discard");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 512, -1, -1));

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 11, 105, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/New Prescription.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 560));

        setSize(new java.awt.Dimension(481, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='0'&&kc<='9')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(this, "Please enter the Total Days of Prescription.");
            evt.consume();
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained

    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked

    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='0'&&kc<='9')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(this, "Please enter the correct Doctor's ID.");
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='0'&&kc<='9')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(this, "Please enter the correct Cost.");
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='0'&&kc<='9')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(this, "Please enter the correct Visit Number.");
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Calendar c=Calendar.getInstance();
int cur_year=c.get(Calendar.YEAR);
int cur_month=c.get(Calendar.MONTH)+1;
int cur_day=c.get(Calendar.DAY_OF_MONTH);
String cm,cd;
if (cur_month<10) {
cm=""+0+cur_month;   } else{ cm=""+cur_month;  }
if(cur_day<10)
{  cd=""+0+cur_day;  }  else  {    cd=""+cur_day;}
String date=cur_year+cm+cd;

if(jTextArea1.getText().isEmpty()||jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty()
||jTextField3.getText().isEmpty()||jTextField4.getText().isEmpty()||jTextField5.getText().isEmpty()) {
if(jTextField1.getText().isEmpty()) {
jLabel7.setVisible(true);}
if(jTextField2.getText().isEmpty()) {
jLabel8.setVisible(true);}
if(jTextField3.getText().isEmpty()) {
jLabel9.setVisible(true);}
if(jTextField4.getText().isEmpty()) {
jLabel10.setVisible(true);}
if(jTextField5.getText().isEmpty()) {
jLabel1.setVisible(true);}
if(jTextArea1.getText().isEmpty()) {
jLabel12.setVisible(true);}
JOptionPane.showMessageDialog(this,"Plase enter the indicated values.");
}
else if(jTextField1.getText().equals("0")||jTextField2.getText().equals("0")||jTextField3.getText().equals("0")||jTextField4.getText().equals("0")||jTextField5.getText().equals("0")||jTextArea1.getText().equals("0")) {
if(jTextField1.getText().equals("0")) {
jLabel7.setVisible(true);
jTextField1.setText("");}
if(jTextField2.getText().equals("0")) {
jLabel8.setVisible(true);
jTextField2.setText("");}
if(jTextField3.getText().equals("0")) {
jLabel9.setVisible(true);
jTextField3.setText("");}
if(jTextField4.getText().equals("0")) {
jLabel10.setVisible(true);
jTextField4.setText("");}
if(jTextField5.getText().equals("0")) {
jLabel11.setVisible(true);
jTextField5.setText("");}
if(jTextField6.getText().equals("0")) {
jLabel14.setVisible(true);
jTextField6.setText("");}
if(jTextArea1.getText().equals("0")) {
jLabel12.setVisible(true);}
JOptionPane.showMessageDialog(this,"Please enter the indicated information.");
}
else if(jTextField1.getText().startsWith("0")||jTextField2.getText().startsWith("0")||jTextField3.getText().startsWith("0")||jTextField4.getText().startsWith("0")||jTextField5.getText().startsWith("0")/*||jTextField6.getText().startsWith("0")*/) {
if(jTextField1.getText().startsWith("0")) {
jTextField1.setText("");
jLabel7.setVisible(true);}
if(jTextField2.getText().startsWith("0")) {
jTextField2.setText("");
jLabel8.setVisible(true);}
if(jTextField3.getText().startsWith("0")) {
jTextField3.setText("");
jLabel9.setVisible(true);}
if(jTextField4.getText().startsWith("0")) {
jTextField4.setText("");
jLabel10.setVisible(true);}
if(jTextField5.getText().startsWith("0")) {
jTextField5.setText("");
jLabel11.setVisible(true);}
if(jTextField6.getText().startsWith("0")) {
jTextField6.setText("");
jLabel14.setVisible(true);}
JOptionPane.showMessageDialog(this,"Please enter the selected value(s) again with no '0' in the begining.");
}
else if(Integer.parseInt(jTextField3.getText())==1&&!(jTextField6.getText().isEmpty())) {
JOptionPane.showMessageDialog(this,"Please press insert again.");
jTextField6.setText("");
}
else if(Integer.parseInt(jTextField3.getText())!=1&&jTextField6.getText().isEmpty()) {
JOptionPane.showMessageDialog(this,"Please enter selected value.");
jLabel14.setVisible(true);}
else if(Integer.parseInt(jTextField4.getText())>45)
{
JOptionPane.showMessageDialog(this,"Please don't give prescription for such a long time.");
jTextField4.setText("");
}
else if(jTextArea1.getText().length()>100){
JOptionPane.showMessageDialog(this, "Prescription too long!");
jTextArea1.setText("");
}
else
{
jLabel7.setVisible(false);
jLabel8.setVisible(false);
jLabel9.setVisible(false);
jLabel10.setVisible(false);
jLabel11.setVisible(false);
jLabel12.setVisible(false);
jLabel14.setVisible(false);
int confirm=JOptionPane.showConfirmDialog(this,"Do you want to make an entry?","Confirm Details",JOptionPane.YES_NO_OPTION);
if(confirm==0) {
try
{
Class.forName("java.sql.DriverManager");
Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/mrproject","root","");
Statement s=conn.createStatement();
String pno=jTextField1.getText();
String dno=jTextField2.getText();
String vno=jTextField3.getText();
String nod=jTextField4.getText();
String cost=jTextField5.getText();
String pres=jTextArea1.getText();
String ref=jTextField6.getText();
int vnoi = Integer.parseInt(vno);
int pnoin= Integer.parseInt(pno);
int dnoin= Integer.parseInt(dno);
String patientcheck="SELECT MAX(pno) FROM patient;";
ResultSet patientcheckrs=s.executeQuery(patientcheck);
if(patientcheckrs.next())
{
if(Integer.parseInt(pno)>Integer.parseInt(patientcheckrs.getString("MAX(pno)")))
{   JOptionPane.showMessageDialog(this,"ERROR: \n No patient ID Found in the record.");
jTextField1.setText("");
jLabel7.setVisible(true);
}
else
{
String doccheck="SELECT MAX(dno) FROM doctor;";
ResultSet doccheckrs=s.executeQuery(doccheck);
if(doccheckrs.next())
{
if(Integer.parseInt(dno)> Integer.parseInt(doccheckrs.getString("MAX(dno)")))
{
JOptionPane.showMessageDialog(this,"ERROR: \n No Doctor with such ID Found in the record.");
jTextField2.setText("");
jLabel8.setVisible(true);
}
else
{
if(!(jTextField6.getText().isEmpty()))
{  String refi=jTextField6.getText();
String check="SELECT pno,dno,MAX(visitno) FROM prescription WHERE pid='"+refi+"';";
ResultSet rscheck=s.executeQuery(check);
if(rscheck.next())
{
int pnoi= Integer.parseInt(rscheck.getString("pno"));
int dnoi= Integer.parseInt(rscheck.getString("dno"));
int visitnoi= Integer.parseInt(rscheck.getString("MAX(visitno)"));
int visitnoin=visitnoi+1;
if((pnoi==pnoin)&&(dnoi==dnoin)&&(visitnoin==vnoi))
{
String q1="INSERT INTO prescription (pno,dno,pric,visitno,pricp_date,days,cost,reference) VALUES ('"+pno+"','"+dno+"','"+pres+"','"+vno+"','"+date+"','"+nod+"','"+cost+"','"+ref+"');";
s.executeUpdate(q1);
String q1_get="SELECT MAX(pid) FROM prescription;";
ResultSet rsget=s.executeQuery(q1_get);
if(rsget.next()) {
String Pres_id=rsget.getString("MAX(pid)");
JOptionPane.showMessageDialog(this,"Data insertion sucessful.."+"\n The prescription's ID is "+Pres_id);
}
new HomePage().setVisible(true);
this.dispose();
}
else
{ JOptionPane.showMessageDialog(this,"ERROR: \n The Entries Made Does not match with that of previous Prescription ID. \n Please enter the Indicated Entries again.");
jTextField1.setText("");
jTextField2.setText("");
jTextField6.setText("");
jTextField3.setText(visitnoin+"");
jLabel7.setVisible(true);
jLabel8.setVisible(true);
jLabel14.setVisible(true);          }
}

}
else
{
String q2="INSERT INTO prescription (pno,dno,pric,visitno,pricp_date,days,cost,reference) VALUES ('"+pno+"','"+dno+"','"+pres+"','"+vno+"','"+date+"','"+nod+"','"+cost+"',NULL);";
s.executeUpdate(q2);
String q2_get="SELECT MAX(pid) FROM prescription;";
ResultSet rsget2=s.executeQuery(q2_get);
if(rsget2.next()) {
String Pres_id=rsget2.getString("MAX(pid)");
JOptionPane.showMessageDialog(this,"Data insertion sucessful.."+"\n The prescription's ID is "+Pres_id);
}
new HomePage().setVisible(true);
this.dispose();
}
}
}
else
{  JOptionPane.showMessageDialog(this,"ERROR: \n No Doctor with such ID Found in the record.");
jTextField2.setText("");
jLabel8.setVisible(true);
}
}
}
else
{
JOptionPane.showMessageDialog(this,"ERROR: \n No patient ID Found in the record.");
jTextField1.setText("");
jLabel7.setVisible(true);
}
}
catch(Exception e)
{JOptionPane.showMessageDialog(this,"error");
JOptionPane.showMessageDialog(this,e.getMessage());
}
}
else
{ }
            
} 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jLabel12.setVisible(false);
jLabel7.setVisible(false);
jLabel14.setVisible(false);
jLabel8.setVisible(false);
jLabel9.setVisible(false);
jLabel10.setVisible(false);
jLabel11.setVisible(false);
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
jTextField4.setText("");
jTextField5.setText("");
jTextField6.setText("");
jTextArea1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate

    }//GEN-LAST:event_jTextField1CaretUpdate

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost

    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='0'&&kc<='9')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(this, "Please enter the correct Patient's ID.");
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
this.setBackground(new Color(0,0,0,0));
jLabel12.setVisible(false);
jLabel7.setVisible(false);
jLabel14.setVisible(false);
jLabel8.setVisible(false);
jLabel9.setVisible(false);
jLabel10.setVisible(false);
jLabel11.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='0'&&kc<='9')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(this, "Please enter the correct reference Number.");
            evt.consume();
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Prescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Prescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables


}
