/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Prankur Agarwal
 */
public class New_Patient extends javax.swing.JFrame {

    /**
     * Creates new form New_Patient
     */
    public New_Patient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField6 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField8 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Star1 = new javax.swing.JLabel();
        Star2 = new javax.swing.JLabel();
        Star3 = new javax.swing.JLabel();
        Star6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Star4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Star7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Star5 = new javax.swing.JLabel();
        Star8 = new javax.swing.JLabel();
        Star9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        Star10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 165, 131, -1));

        jComboBox4.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "A+", "B+", "O+", "AB+", "A-", "B-", "O-", "AB-" }));
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 107, -1, -1));

        jTextField8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 218, 131, -1));

        jButton3.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(225, 0, 0));
        jButton3.setText("DISCARD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));

        jButton1.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        jLabel19.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel19.setText("Patient's Last Name:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 65, -1, -1));

        jButton2.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel10.setText("Disease:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 218, -1, -1));

        jTextField10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 218, 123, -1));

        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 60, 131, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        Star1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Star1.setForeground(new java.awt.Color(255, 0, 0));
        Star1.setText("*");
        getContentPane().add(Star1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        Star2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Star2.setForeground(new java.awt.Color(255, 0, 0));
        Star2.setText("*");
        getContentPane().add(Star2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 63, -1, -1));

        Star3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Star3.setForeground(new java.awt.Color(255, 0, 0));
        Star3.setText("*");
        getContentPane().add(Star3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 108, -1, -1));

        Star6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Star6.setForeground(new java.awt.Color(255, 0, 0));
        Star6.setText("*");
        getContentPane().add(Star6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 221, -1, -1));

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel1.setText("Patient's First Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        Star4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Star4.setForeground(new java.awt.Color(255, 0, 0));
        Star4.setText("*");
        getContentPane().add(Star4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 281, -1, -1));

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 123, -1));

        Star7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Star7.setForeground(new java.awt.Color(255, 0, 0));
        Star7.setText("*");
        getContentPane().add(Star7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 111, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel2.setText("Blood Group:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        Star5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Star5.setForeground(new java.awt.Color(255, 0, 0));
        Star5.setText("*");
        getContentPane().add(Star5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 168, -1, -1));

        Star8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Star8.setForeground(new java.awt.Color(255, 0, 0));
        Star8.setText("*");
        getContentPane().add(Star8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 168, -1, -1));

        Star9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Star9.setForeground(new java.awt.Color(255, 0, 0));
        Star9.setText("*");
        getContentPane().add(Star9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 221, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel4.setText("Gender:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 113, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel5.setText("Mobile Number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jRadioButton1.setText("Male");
        jRadioButton1.setBorder(null);
        jRadioButton1.setContentAreaFilled(false);
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 113, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.setBorder(null);
        jRadioButton2.setContentAreaFilled(false);
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 111, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel6.setText("Relative's Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 170, -1, -1));

        jLabel18.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel18.setText("Today's Date:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 14, -1, -1));

        jLabel8.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel8.setText("Father's Name:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 223, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jComboBox1.setToolTipText("YEAR");
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 11, 80, -1));

        jLabel9.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel9.setText("Address:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 363, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox2.setToolTipText("MONTH");
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 11, -1, -1));

        jTextField5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 165, 123, -1));

        jComboBox3.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox3.setToolTipText("DATE");
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 11, -1, -1));

        Star10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Star10.setForeground(new java.awt.Color(255, 0, 0));
        Star10.setText("*");
        getContentPane().add(Star10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 374, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jLabel3.setText("Date Of Birth:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 286, -1, -1));

        jComboBox5.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Year--", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jComboBox6.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Month--", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 280, -1, -1));

        jComboBox7.setFont(new java.awt.Font("Bradley Hand ITC", 1, 16)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Date--", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 280, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/New_Patient.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 460));

        setSize(new java.awt.Dimension(751, 455));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='a'&&kc<='z')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE)
            ||(kc>='A'&&kc<='Z')||(kc=='.')||(kc==KeyEvent.VK_SPACE))) {
        JOptionPane.showMessageDialog(this, "Please enter the correct Name.");
        evt.consume();
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='a'&&kc<='z')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE)
            ||(kc>='A'&&kc<='Z')||(kc=='.')||(kc==KeyEvent.VK_SPACE))) {
        JOptionPane.showMessageDialog(this, "Please enter the correct Name.");
        evt.consume();
        }
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Star1.setVisible(false);
        Star2.setVisible(false);
        Star3.setVisible(false);
        Star4.setVisible(false);
        Star5.setVisible(false);
        Star9.setVisible(false);
        Star6.setVisible(false);
        Star7.setVisible(false);
        Star8.setVisible(false);
        Star10.setVisible(false);
        Calendar c=Calendar.getInstance();
        int cur_year=c.get(Calendar.YEAR);
        int cur_month=c.get(Calendar.MONTH)+1;
        int cur_day=c.get(Calendar.DAY_OF_MONTH);
        String cm,cd;
        if (cur_month<10) {
            cm=""+0+cur_month;   } else{ cm=""+cur_month;  }
        if(cur_day<10)
        {  cd=""+0+cur_day;  }  else  {    cd=""+cur_day;}
        String date=cur_year+cm+cd;
        DefaultComboBoxModel com=(DefaultComboBoxModel)jComboBox4.getModel();
        DefaultComboBoxModel com1=(DefaultComboBoxModel)jComboBox5.getModel();
        DefaultComboBoxModel com2=(DefaultComboBoxModel)jComboBox6.getModel();
        DefaultComboBoxModel com3=(DefaultComboBoxModel)jComboBox7.getModel();
        String dy= (String)jComboBox5.getSelectedItem();
        int y = Integer.parseInt(dy);
        int ay= cur_year-(y);
        String dm= (String)jComboBox6.getSelectedItem();
        int m = Integer.parseInt(dm);
        int am= cur_month-(m);
        String dd= (String)jComboBox7.getSelectedItem();
        int d = Integer.parseInt(dd);
        int ad= cur_day-(d);
        int age=0;
        if(am<0){
            age = ay - 1; 
        }
        else if(am>0)
        {
          age = ay;  
        }
        else if(am==0){
        if(ad<0){
        age = ay - 1;
        }
        else if(ad>=0){
             age = ay;
         }
        }
        String final_age = String.valueOf(age);
        if(jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty()||jComboBox4.getSelectedIndex()==0||
jTextField5.getText().isEmpty()||jTextField6.getText().isEmpty()||jTextField8.getText().isEmpty()||
jTextField10.getText().isEmpty()||jComboBox5.getSelectedIndex()==0||
jComboBox6.getSelectedIndex()==0||jComboBox7.getSelectedIndex()==0||jTextArea1.getText().isEmpty()) {
if(jTextField1.getText().isEmpty()) {
   Star1.setVisible(true);}
if(jTextField2.getText().isEmpty()) {
   Star2.setVisible(true);}
if(jComboBox4.getSelectedIndex()==0) {
   Star3.setVisible(true);}
if(jComboBox5.getSelectedIndex()==0||jComboBox6.getSelectedIndex()==0||jComboBox7.getSelectedIndex()==0) {
   Star4.setVisible(true);}        
if(jTextField5.getText().isEmpty()) {
   Star5.setVisible(true);}
if(jTextField6.getText().isEmpty()) {
                Star8.setVisible(true);}
            if(jTextField8.getText().isEmpty()) {
                Star9.setVisible(true);}
            if(jTextField10.getText().isEmpty()) {
                Star6.setVisible(true);}
            if(!(jRadioButton1.isSelected())&&!(jRadioButton2.isSelected())) {
                Star7.setVisible(true);}
            JOptionPane.showMessageDialog(this,"Please Enter the indicated values.");
        }
if(jTextArea1.getText().isEmpty()) {
                Star10.setVisible(true);}
        else if(jTextField5.getText().length()!=10) {
            JOptionPane.showMessageDialog(this,"Please enter the correct mobile Number.");
            jTextField5.setText("");    
        }
       else if(jTextField5.getText().startsWith("0"))
        {
            JOptionPane.showMessageDialog(this,"Please enter the mobile number correctly.");
            jTextField5.setText("");
            Star5.setVisible(true);
        }
        else if(jTextField6.getText().startsWith(" ")||jTextField8.getText().startsWith(" "))
        {
            if(jTextField6.getText().startsWith(" "))
            {
                jTextField6.setText("");
                Star8.setVisible(true);
            }
            else if(jTextField8.getText().startsWith(" "))
            {
                jTextField8.setText("");
                Star9.setVisible(true);
            }
            JOptionPane.showMessageDialog(this,"Please enter the indicated fields properly.");
        }
        else  {
            int confirm=JOptionPane.showConfirmDialog(this,"Do you want to make an entry ?","Confirm Details",JOptionPane.YES_NO_OPTION);
            if(confirm==0) {
                try {
                    Star1.setVisible(false);  Star3.setVisible(false);
                    Star6.setVisible(false); Star4.setVisible(false);
                    Star7.setVisible(false); Star5.setVisible(false);
                    Star8.setVisible(false); Star9.setVisible(false);
                    Star2.setVisible(false);
                    String fname=jTextField1.getText();
                    String sname=jTextField2.getText();
                    String name=fname+" "+sname;
                    String bg=(String) com.getSelectedItem();
                    String disease=jTextField10.getText();
                    String mobileno=jTextField5.getText();
                    String reln=jTextField6.getText();
                    String fathern=jTextField8.getText();
                    String add=jTextArea1.getText();
                    Class.forName("java.sql.DriverManager");
                    Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/mrproject","root","");
                    Statement s =(Statement) con.createStatement();
                    if(jRadioButton1.isSelected()) {
                        String gender="male";
                        String q="INSERT INTO patient (p_name,b_gp,age,gender,rel_name,father_name,address,disease,mobileno,entry_date) VALUES('"+name+"','"+bg+"','"+final_age+"','"+gender+"','"+reln+"','"+fathern+"','"+add+"','"+disease+"','"+mobileno+"','"+date+"');";
                        s.executeUpdate(q);}
                    else if(jRadioButton2.isSelected()) {
                        String gender="female";
                        String q="INSERT INTO patient (p_name,b_gp,age,gender,rel_name,father_name,address,disease,mobileno,entry_date) VALUES('"+name+"','"+bg+"','"+final_age+"','"+gender+"','"+reln+"',"+fathern+"','"+add+"','"+disease+"','"+mobileno+"','"+date+"');";
                        s.executeUpdate(q);}

                    String q1="SELECT MAX(pno) FROM patient;";
                    ResultSet rs1=s.executeQuery(q1);
                    if(rs1.next())
                    {
                        String Patient_id=rs1.getString("MAX(pno)");
                        JOptionPane.showMessageDialog(this,"Insertion sucessful..."+"\n The Patient's ID is "+Patient_id);
                    }
                    new HomePage().setVisible(true);
                    this.dispose();
                } catch (Exception e) {JOptionPane.showMessageDialog(this, e.getMessage()); }
            } else{ }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextArea1.setText("");
        jTextField1.setText("");
    buttonGroup1.clearSelection();
        jComboBox4.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        jComboBox6.setSelectedIndex(0);
       jComboBox7.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        jTextField2.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField8.setText("");
        jTextField10.setText("");
        Star1.setVisible(false);
        Star2.setVisible(false);
        Star3.setVisible(false);
        Star4.setVisible(false);
        Star5.setVisible(false);
        Star6.setVisible(false);
        Star7.setVisible(false);
        Star8.setVisible(false);
        Star9.setVisible(false);
        Star10.setVisible(false);        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='a'&&kc<='z')||(kc>='A'&&kc<='Z')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE))) {
            JOptionPane.showMessageDialog(this, "Please enter the disease.");
            evt.consume();
        }
    }//GEN-LAST:event_jTextField10KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='a'&&kc<='z')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE)
            ||(kc>='A'&&kc<='Z')||(kc=='.'))) {
        JOptionPane.showMessageDialog(this, "Please enter the correct name of the Patient.");
        evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='a'&&kc<='z')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE)
            ||(kc>='A'&&kc<='Z')||(kc=='.'))) {
        JOptionPane.showMessageDialog(this, "Please enter the correct name of the Patient.");
        evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        char kc=evt.getKeyChar();
        if(!((kc>='0'&&kc<='9')||(kc==KeyEvent.VK_BACK_SPACE)||(kc==KeyEvent.VK_DELETE)))
        {
            JOptionPane.showMessageDialog(this, "Please enter the correct mobile number.");
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
this.setBackground(new Color(0,0,0,0));
jComboBox1.setEnabled(false);
jComboBox2.setEnabled(false);
jComboBox3.setEnabled(false);
     
Calendar c = new GregorianCalendar();
int month =c.get(Calendar.MONTH);
int year =c.get(Calendar.YEAR);
int day =c.get(Calendar.DAY_OF_MONTH);
while(year>=1990)
{
jComboBox1.addItem(year);
year--;
}
jComboBox2.setSelectedIndex(month);
jComboBox3.setSelectedIndex(day-1);
Star1.setVisible(false);
Star2.setVisible(false);
Star3.setVisible(false);
Star4.setVisible(false);
Star5.setVisible(false);
Star6.setVisible(false);
Star7.setVisible(false);
Star8.setVisible(false);
Star9.setVisible(false);
Star10.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Star1;
    private javax.swing.JLabel Star10;
    private javax.swing.JLabel Star2;
    private javax.swing.JLabel Star3;
    private javax.swing.JLabel Star4;
    private javax.swing.JLabel Star5;
    private javax.swing.JLabel Star6;
    private javax.swing.JLabel Star7;
    private javax.swing.JLabel Star8;
    private javax.swing.JLabel Star9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
